#version: v2

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: srk
      POSTGRES_PASSWORD: 1329
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
        #- ./init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
     db_data:       
