# added version tag
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          #1docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api ./backend
            docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api:${{ github.sha }} ./backend
            docker tag ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api:latest                  #Build ONCE, tag twice

      - name: Push Docker image
        run: |
          #1docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-apii
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-api:latest
